#!/bin/bash

# TODO: check if $1 matches date

# cleanup html folder
echo "deleting files from /var/www/html/"
rm -R /var/www/html/*

# restore files
echo "restoring files from /backups/backup_$1.tar.gz to /var/www/html"
tar -xzf /backups/backup_$1.tar.gz --directory="/var/www/html/"

# update wp-config.php
sed -i s/"define('DB_NAME', '.*');"/"define('DB_NAME', '$MYSQL_ENV_MYSQL_DATABASE');"/g /var/www/html/wp-config.php
sed -i s/"define('DB_USER', '.*');"/"define('DB_USER', '$MYSQL_ENV_MYSQL_USER');"/g /var/www/html/wp-config.php
sed -i s/"define('DB_PASSWORD', '.*');"/"define('DB_PASSWORD', '$MYSQL_ENV_MYSQL_PASSWORD');"/g /var/www/html/wp-config.php
sed -i s/"define('DB_HOST', '.*');"/"define('DB_HOST', '$MYSQL_PORT_3306_TCP_ADDR:$MYSQL_PORT_3306_TCP_PORT');"/g /var/www/html/wp-config.php

# set correct file owner
chown -R www-data:www-data /var/www/html

# restore database
echo "restoring data from mysql dump file /backups/backup_$1.sql.bz2"
bunzip2 < /backups/backup_$1.sql.bz2 | mysql -u$MYSQL_ENV_MYSQL_USER -p $MYSQL_ENV_MYSQL_DATABASE -p$MYSQL_ENV_MYSQL_PASSWORD -h $MYSQL_PORT_3306_TCP_ADDR

echo 'Finished: SUCCESS'
