#!/bin/bash

cleanup() {
  echo "Cleanup backup older than $CLEANUP_OLDER_THAN days"
  toberemove=$(find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN | wc -l)
  echo "Will try to remove $toberemove files"
  find /backups/ -type f -not -name ".*" -mtime +$CLEANUP_OLDER_THAN -exec rm {} \;
}

if [ -z "$MYSQL_ENV_MYSQL_USER" ]; then echo "Error: MYSQL_ENV_MYSQL_USER not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$MYSQL_ENV_MYSQL_DATABASE" ]; then echo "Error: MYSQL_ENV_MYSQL_DATABASE not set"; echo "Finished: FAILURE"; exit 1; fi
if [ -z "$MYSQL_ENV_MYSQL_PASSWORD" ]; then echo "Error: MYSQL_ENV_MYSQL_PASSWORD not set"; echo "Finished: FAILURE"; exit 1; fi

if [ -n "$CLEANUP_OLDER_THAN" ]; then cleanup;  fi

echo 'creating backup archive of /var/www/html'
tar --create --gzip -vv --directory="/var/www/html/" --file="/backups/backup_`date '+%Y%m%d%H%M'`.tar.gz" "./"

echo 'creating database dump'
mysqldump -h mysql --add-drop-table -u$MYSQL_ENV_MYSQL_USER -p $MYSQL_ENV_MYSQL_DATABASE --password=$MYSQL_ENV_MYSQL_PASSWORD | bzip2 -c > /backups/backup_`date '+%Y%m%d%H%M'`.sql.bz2

echo 'Finished: SUCCESS'
